name: Test Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'src/**'
      - '.github/workflows/test-release.yml'

permissions:
  contents: read
  id-token: write  # Required for OIDC trusted publishing

jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/subprocess-vcr/
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build package
        run: |
          uv build

      - name: Publish to TestPyPI
        run: |
          uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always
